### ISSUE TITLE
Make it hyperscript-agnostic 

### ISSUE THREAD

**Issue by vdanchenkov** [colingourlay/hyperstyles#1]
I've been thinking of similar library for React when I found this one. I think we can rewrite it to remove dependency on virtual dom. It will allow library to be used with hyperscript or react-hyperscript, but will require one breaking change of usage pattern.

    var hyperstyles = require('hyperstyles')(require('virtual-dom/virtual-hyperscript'));
    var h = hyperstyles(require('./car.css'));

@colingourlay, I will work on implementation in a couple of weeks and will provide a PR if you are ok with this change.

**Comment by colingourlay** [comment]
Thanks for the suggestion, @vdanchenkov!

I've been considering this myself for a while, and your message prompted me to take the time to actually implement it.

I've just released v2.0.0 which has stripped out the `virtual-hyperscript` dependency, and allows you to pass in your own DOM building function and styles, or partially apply the arguments, using the same pattern you've suggested.

Please have a play around with it and let me know where it breaks. I'm always happy to consider pull requests if you think there's a better way to do this.

Cheers!
