### ISSUE TITLE
React components supplied as first argument should be ignored.

### ISSUE THREAD

**Issue by vdanchenkov** [colingourlay/hyperstyles#2]
Looks like transformation code tries to parse it like a string.

Given code:

    var h = hyperstyles(reactCreateElement, exampleStyles);	
    var component = require('react').createClass({
		render: function() {
			return reactCreateElement('div')
		}
	});

	h(component); 

Produce error:

     /Users/user/work/hyperstyles/transform.js:33
                        throw new Error('"' + styleName + '" doesn\'t exist in this CSS Module');
                              ^
     Error: "" doesn't exist in this CSS Module
          at /Users/user/work/hyperstyles/transform.js:33:10

**Comment by colingourlay** [comment]
Ah yes! When I expanded the scope of this module from just `virtual-hyperscript`, I forgot that React lets you pass in a component/class as the first argument to `React.createElement`.

This is also the case in other libraries such as `hyperscript` and `crel` which allow you to supply a DOM node as the first argument.

I'll add in an exception when the first argument is not a string, so skip past the id/class selector parsing step that would cause this error to be thrown.

Thanks for catching this out!

**Comment by colingourlay** [comment]
I've just published version 3.0.0 which has an all new dependency-free transform, which takes special care to only mutate the arguments it needs to convert `styleName`s to `styleClass`es, including those found in the tagName.

This will allow React to do what it needs to, including passing through a class/component as the first argument, `null` as the 2nd (which will be converted into a props object in rare circumstances), and an arbitrary number of children.

This will also fix issue #3 too so I plan on closing both issues now, and if you still have problems, we'll start fresh on a new issue.

Thanks again for taking the time to test hyperstyles and opening tickets. I really appreciate it!
